# Generated by Django 3.1.4 on 2021-02-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_id',
            new_name='exercising_id',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciser',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='length_in_min',
        ),
        migrations.RemoveField(
            model_name='lift',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='lift',
            name='lifter',
        ),
        migrations.RemoveField(
            model_name='lift',
            name='one_rep_max',
        ),
        migrations.RemoveField(
            model_name='lift',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='lift',
            name='weight',
        ),
        migrations.CreateModel(
            name='LiftSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('one_rep_max', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('lift_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.lift')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Exerciser',
            fields=[
                ('ex_id', models.BinaryField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('length_in_min', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.exercise')),
                ('exerciser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.user')),
            ],
        ),
    ]
