# Generated by Django 3.1.7 on 2021-04-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='entry_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exerciser',
            name='entry_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gain',
            name='entry_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='liftset',
            name='entry_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loss',
            name='entry_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='todaysweight',
            name='entry_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
