# Generated by Django 3.1.4 on 2021-03-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_auto_20210228_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciser',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='exerciser',
            old_name='exerciser_id',
            new_name='exerciser',
        ),
    ]
