# Generated by Django 3.1.4 on 2021-04-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_auto_20210309_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addfriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.friend')),
                ('exercize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.exercise')),
                ('exercizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.exerciser')),
                ('gainz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.gain')),
                ('lift_zet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.liftset')),
                ('liftz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.lift')),
                ('lozz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.loss')),
                ('todayz_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.todaysweight')),
                ('total_gainz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.totalgain')),
                ('total_lozz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.totalloss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.user')),
            ],
        ),
    ]
