# Generated by Django 3.1.4 on 2021-03-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_auto_20210301_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciser',
            name='username',
        ),
    ]
