# Generated by Django 3.1.4 on 2021-04-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='addfriend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.friend'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='exercize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.exercise'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='exercizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.exerciser'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='gainz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.gain'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lift_zet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.liftset'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='liftz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.lift'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lozz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.loss'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='todayz_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.todaysweight'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_gainz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.totalgain'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_lozz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.totalloss'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.user'),
        ),
    ]
